eureka:
  instance:
    client:
      fetch-registry: true
      register-with-eureka: true
    prefer-ip-address: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

